"""hashed otps with attempt limits, password_changed_at

Revision ID: 61b787cb4910
Revises: a57c0199b0e2
Create Date: 2026-10-01 16:36:34.683934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b787cb4910'
down_revision: Union[str, Sequence[str], None] = 'a57c0199b0e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing OTPs were stored in plain text and expire within minutes anyway: delete them,
    # so the new NOT NULL otp_hash column can be added. Users just request a new code.
    op.execute("DELETE FROM password_reset_tokens")
    op.execute("DELETE FROM signup_otp_tokens")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('otp_hash', sa.String(), nullable=False))
    op.add_column('password_reset_tokens', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    op.drop_index(op.f('ix_password_reset_tokens_otp'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.drop_column('password_reset_tokens', 'otp')
    op.add_column('signup_otp_tokens', sa.Column('otp_hash', sa.String(), nullable=False))
    op.add_column('signup_otp_tokens', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('signup_otp_tokens', 'otp')
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM password_reset_tokens")
    op.execute("DELETE FROM signup_otp_tokens")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_changed_at')
    op.add_column('signup_otp_tokens', sa.Column('otp', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('signup_otp_tokens', 'attempts')
    op.drop_column('signup_otp_tokens', 'otp_hash')
    op.add_column('password_reset_tokens', sa.Column('otp', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_otp'), 'password_reset_tokens', ['otp'], unique=False)
    op.drop_column('password_reset_tokens', 'attempts')
    op.drop_column('password_reset_tokens', 'otp_hash')
    # ### end Alembic commands ###
