"""website crawl tables

Revision ID: a57c0199b0e2
Revises: 4e0b41ddf85c
Create Date: 2026-10-01 12:58:09.024109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57c0199b0e2'
down_revision: Union[str, Sequence[str], None] = '4e0b41ddf85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('pages_seen', sa.Integer(), nullable=False),
    sa.Column('pages_added', sa.Integer(), nullable=False),
    sa.Column('pages_updated', sa.Integer(), nullable=False),
    sa.Column('pages_unchanged', sa.Integer(), nullable=False),
    sa.Column('pages_removed', sa.Integer(), nullable=False),
    sa.Column('pages_failed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_runs_id'), 'crawl_runs', ['id'], unique=False)
    op.create_table('crawled_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_crawled', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_changed', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawled_pages_id'), 'crawled_pages', ['id'], unique=False)
    op.create_index(op.f('ix_crawled_pages_url'), 'crawled_pages', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawled_pages_url'), table_name='crawled_pages')
    op.drop_index(op.f('ix_crawled_pages_id'), table_name='crawled_pages')
    op.drop_table('crawled_pages')
    op.drop_index(op.f('ix_crawl_runs_id'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    # ### end Alembic commands ###
